Gaiak:
  - Creeper
Metrics: true
Language: en
Rewards:
  Vault:
    Enabled: true
    Winner: 5
    Second: 5
    Third: 5
    Rest: 5
  PlayerPoints:
    Enabled: false
    Winner: 5
    Second: 5
    Third: 5
    Rest: 5
  Command:
    Enabled: truw
    Winner: 'bb leave'
    Second: 'bb leave'
    Third: 'bb leave'
    Rest: 'bb leave'
